program ashole;
   type mas = array [1 .. 30, 1 .. 30] of boolean;
   var laukas , kelias: mas;
       kr : record
              x, y : integer
            end;


   procedure ejimas ( var kryptis: integer; x, y: integer );
   begin
        if true then
         else
            begin
             repeat
              inc (ejimai);

             until not laukas [x,y];

            end
   end;

begin
   assign (f, 't.dat');
   reset (f);
   readln (f, x1, y1):
   for ck1 := 1 to x1 do
     begin
      for ck2 := 1 to y1 do read (f, laukas [ck1,ck2]);
      readln (f)
     end;
   ejimas (1, 1, 1, kelias);
   for y := 1 to y1 do
      for x := 1 to x1 do


end.